<?php echo $this->htmlEscape($this->getMethod()->getTitle()); ?><br />
<?php if ($_img = $this->getPaymentImageSrc($this->getMethodCode())): ?>
	<div style="padding:10px 15px 15px;">
		<img src="<?php echo $_img ?>" alt="" /><br />
	</div>
<?php endif; ?>
<?php if ($this->getInfo()->getLastTransId() == ''): ?>
	<? if($this->getInfo()->getMethodInstance()->isInvoice()): ?>
		<em><?php echo Mage::helper('payanyway')->__('Invoice will be created after you place an order.') ?></em>
	<? else: ?>
		<em><?php echo Mage::helper('payanyway')->__('You will be redirected to the payment system page when you place an order.') ?></em>
	<? endif;?>
<?php else: ?>
    <?php echo Mage::helper('payanyway')->__('Payanyway Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) ?><br />
<?php endif; ?>
