<?php $invoice = $this->getData("invoice") ?>
<div class="page-head">
	<?php if ($invoice['status'] === 'CREATED'): ?>
		<h3><?php echo Mage::helper('payanyway')->__('Invoice was created') ?></h3>
		<?php if ($invoice['system'] === 'payanyway_banktransfer'): ?>
			<?php echo Mage::helper('payanyway')->__("Transaction is registered for processing. To complete your payment please <a onclick='window.open(%s);return false;' href='#'>print receipt</a> and make payment in bank office.", '"http://'.$this->getPaymentAction().'/wiretransferreceipt.htm?transactionId='.$invoice['transaction'].'&paymentSystem.unitId='.$invoice['unitid'].'","newwindow","1,0,0,0,0,resizable=1,scrollbars=1,width=730,height=670"') ?>
		<?php elseif ($invoice['system'] == 'payanyway_post'): ?>
			<?php echo Mage::helper('payanyway')->__('Transaction is registered for processing. To complete your payment please <a target="_blank" href="https://%s/mailofrussiablank.htm?operationId=%s">print post ticket</a> and proceed with payment in any <a target="_blank" href="http://www.russianpost.ru">Russian Post</a> post office.To view post ticket in PDF format you should have a program <a target="_blank" href="http://get.adobe.com/reader/">Adobe Acrobat Reader</a> installed.', $this->getPaymentAction(), $invoice['transaction']) ?>
		<?php else:?>
			<?php if ($invoice['system'] == 'payanyway_ciberpay'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for CiberPay is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with CiberPay system using following <b>MONETA.RU</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_comepay'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for ComePay is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with ComePay cash payment terminals using following <b>PayAnyWay</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_contact'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for Contact is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with Contact payment system using following <b>MONETA.RU</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_elecsnet'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for Elecsnet is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with Elecsnet cash payment terminals using following <b>PayAnyWay</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_euroset'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for Euroset is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with Euroset using following <b>PayAnyWay</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_gorod'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for Federal system GOROD is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with Federal system GOROD using following <b>PayAnyWay</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_forward'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for Forward Mobile is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with Forward Mobile system using following <b>MONETA.RU</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_mcb'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for MosCreditBank is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with MosCreditBank cash payment terminals using following <b>MONETA.RU</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_novoplat'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for NovoPlat is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with NovoPlat system using following <b>PayAnyWay</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_platika'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for PLATiKA is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with PLATiKA system using following <b>MONETA.RU</b> account number:') ?></p>
			<?php elseif ($invoice['system'] == 'payanyway_sberbank'):?>
				<h4><?php echo Mage::helper('payanyway')->__('Contract number for Sberbank is: %s', $invoice['transaction']) ?></h4>
				<p><?php echo Mage::helper('payanyway')->__('Transaction is registered. Please proceed payment with Sberbank using following <b>MONETA.RU</b> account number:') ?></p>
			<?php endif; ?>
				
			<p><?php echo $invoice['transaction'] ?></p>
			
			<?php if ($invoice['system'] == 'payanyway_sberbank'):?>
				<p><?php echo Mage::helper('payanyway')->__('Or click on <a href="https://online.sberbank.ru/PhizIC/private/payments/servicesPayments/edit.do?recipient=113368&field(_TCM_IDENT_WlsZid1)=%s">link</a> to pay by SberbankOnline.', $invoice['transaction']) ?></p>
			<?php endif; ?>
			
			<p><?php echo Mage::helper('payanyway')->__('Total amount: %s', $invoice['amount']) ?></p>
		<?php endif; ?>
	<?php else: ?>
		<h3><?php echo Mage::helper('payanyway')->__("Error <a onclick='window.open(%s)'>occured</a> during creating invoice", '"http://'.$this->getPaymentAction().'/wiretransferreceipt.htm?transactionId='.$invoice['transaction'].'&paymentSystem.unitId='.$invoice['unitid'].'","newwindow","1,0,0,0,0,resizable=1,scrollbars=1,width=730,height=670"') ?></h3>
		<p><?php echo $invoice['error_message']; ?></p>
	<?php endif; ?>
    
</div>
