<div class="page-title">
    <h1><?php echo $this->__('Redirecting...') ?></h1>
</div>
<div>
	<form name="payanyway" id="payanyway_payment_form" action="<?php echo $this->getFormAction();?>" method="POST">
	<?php if (is_array($this->getFormData())): ?>
		<?php foreach ($this->getFormData() as $name => $value): ?>
			<input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>"/>
		<?php endforeach; ?>
	<?php endif; ?>
	</form>
</div>			
<script type="text/javascript">
//<![CDATA[
	document.getElementById('payanyway_payment_form').submit();
//]]>
</script>            
